import './globals.css'
import {Inter} from 'next/font/google'
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";
import styles from "@/app/page.module.css";
import {Session} from "next-auth";
import {ReactNode} from "react";
const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface MyProps {
  children?: ReactNode;
  session:Session;
}
export default function RootLayout(props:MyProps) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Provider session={props.session}>


        {/*<main className={styles.main}> */}
        <div className={styles.col}>
          <div className={styles.row}>
            <Nav/>
          </div>
          <div className={styles.row}>
            <div className={styles.col}>
              {props.children}
            </div>
          </div>
        </div>

        {/*</main>*/}
      </Provider>
      </body>
      </html>
  )
}
